### ISSUE TITLE
Are the port numbers correct:  KAFKA_BROKERCONNECT: "kafka1:29092,kafka2:29093"

### ISSUE THREAD

**Issue by groovyman** [skylvr1289/sample_kafka#1]
Dear friends,
i took a look at the docker-compose-kafka-cluster.yaml and i am wondering, if 29092 and 29093 are portnumbers, as far as i can see is that kafka1 does only provide for a portnummber 9092!  What does the leading 2 mean, is it a typo?

**Comment by skylvr1289** [comment]
Hi @groovyman,
It is not a typo. It is kept like that purposefully. 
Kafka brokers communicate between themselves, usually on the internal network. our KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL which communicate on internal ports 29092 & 29093.
This is a good read : [link](https://www.confluent.io/blog/kafka-listeners-explained/)
